#!/bin/bash
for f in tests/*.cl
do
    if [[ $# = 0 ]]  
    then 
        echo "number of lines of diff for: $f"
        diff -U 0 <(./mysemant $f) <(./theirsemant $f) | grep ^@ | wc -l
    elif [[ $# = 2 ]]
    then 
        echo "mysemant output for: $f"
        ./mysemant -s $f
    elif [[ $# = 3 ]]
    then 
        echo "theirsemant output for: $f"
        ./theirsemant -s $f
    elif [[ $# = 4 ]]
    then 
        echo "parser output for: $f"
        ./runparser $f
    else
        echo "diffing semant output for: $f"
        diff <(./mysemant $f) <(./theirsemant $f)
    fi
done